blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.BlogPageView.as_view(),name='blog-page')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('core.urls')),
    path('admin/', admin.site.urls),
    path('projects/',include('projects.urls')),
    path('photos/',include('photo.urls')),
    path('travel/',include('travel.urls')),
    path('blogs/',include('blog.urls')),
]

projects/models.py
from django.db import models
from core.models import PostBase


class ProjectPost(PostBase):
    differentField=(
        ("Machine Learning","Machine Learning"),
        ("BlockChain ","BlockChain"),
        ("3D Art","3D Art"),
        ("Side Project","Side Project"),
    )
    topic = models.CharField(max_length=100,choices=differentField)
    image= models.ImageField(null=True,blank=True,upload_to='images/projects/')
    maincontent = models.TextField(null=True,blank=True, default='default') 
    
    #test = models.CharField(null=True,blank=True,max_length=20)

templates/form_templates/project_additional_fields.html
<div class="form-field">Topic</div>
<div id="form-topic">
    <select name="topic" required id="id_topic">
        <option value selected>----------</option>
        <option value selected>Machine Learning</option>
        <option value selected>BlockChain</option>
        <option value selected>3D Art</option>
    </select>
</div>
<div class="form-field">justtest</div>
<div id="form-justtest">{{ form.just_test }}</div>
<input type="text" name="form_project_justtest">